plugins { id 'com.android.application' }

android {
    namespace 'com.caeless.monstrinhos'
    compileSdk 35
    defaultConfig {
        applicationId 'com.caeless.monstrinhos'
        minSdk 26
        targetSdk 35
        versionCode 4240
        versionName '4.2.4-achievement-stability'
    }
}
