package com.caeless.monstrinhos;

import android.content.Context;
import android.content.SharedPreferences;

final class GameState {
    private static final String PREFS="monstrinhos_save_v1";
    int coins=0,stars=0,level=1,eggs=0,houseLevel=1,streak=0,bestStreak=0,soundOn=1,vibrationOn=1,dailyClaimDay=0,missionsDone=0,missionRewardTier=0,totalHatched=0,bossWins=0,reactionsUnlocked=1,favoriteMonster=0,xp=0,playerLevel=1,bestScore=0,totalPlays=0,perfectBosses=0,houseVisits=0,carePoints=0,dailyStreak=0,bestDailyStreak=0,lastClaimDay=0,challengeWins=0,challengeBest=0,hatchPity=0,rareMonsters=0,bossTokens=0,bossChestLevel=0,reactionUses=0,friendshipLevel=1,houseDecor=0,houseDecorOwned=1,sessionWins=0,sessionPerfect=0,saveSchema=2,reducedMotion=0,largeText=0,hintsOn=1,highContrast=0,colorBlindMode=0,accessibilityAnnouncements=1,levelAttempts=0,levelFailures=0,bossFailures=0;
    long ownedMask=1L,achievementMask=0L; private String levelStars="";
    static GameState load(Context c){SharedPreferences p=c.getSharedPreferences(PREFS,Context.MODE_PRIVATE);GameState s=new GameState();s.coins=p.getInt("coins",0);s.stars=p.getInt("stars",0);s.level=p.getInt("level",1);s.eggs=p.getInt("eggs",0);s.houseLevel=p.getInt("house_level",1);s.ownedMask=p.getLong("owned_mask",1L);s.achievementMask=p.getLong("achievement_mask",0L);s.levelStars=p.getString("level_stars","");s.dailyClaimDay=p.getInt("daily_claim_day",0);s.missionsDone=p.getInt("missions_done",0);s.streak=p.getInt("streak",0);s.bestStreak=p.getInt("best_streak",0);s.soundOn=p.getInt("sound_on",1);s.vibrationOn=p.getInt("vibration_on",1);s.missionRewardTier=p.getInt("mission_reward_tier",0);s.totalHatched=p.getInt("total_hatched",0);s.bossWins=p.getInt("boss_wins",0);s.reactionsUnlocked=p.getInt("reactions_unlocked",1);s.favoriteMonster=p.getInt("favorite_monster",0);s.xp=p.getInt("xp",0);s.playerLevel=p.getInt("player_level",1);s.bestScore=p.getInt("best_score",0);s.totalPlays=p.getInt("total_plays",0);s.perfectBosses=p.getInt("perfect_bosses",0);s.houseVisits=p.getInt("house_visits",0);s.carePoints=p.getInt("care_points",0);s.dailyStreak=p.getInt("daily_streak",0);s.bestDailyStreak=p.getInt("best_daily_streak",0);s.lastClaimDay=p.getInt("last_claim_day",0);s.challengeWins=p.getInt("challenge_wins",0);s.challengeBest=p.getInt("challenge_best",0);s.hatchPity=p.getInt("hatch_pity",0);s.rareMonsters=p.getInt("rare_monsters",0);s.bossTokens=p.getInt("boss_tokens",0);s.bossChestLevel=p.getInt("boss_chest_level",0);s.reactionUses=p.getInt("reaction_uses",0);s.friendshipLevel=p.getInt("friendship_level",1);s.houseDecor=p.getInt("house_decor",0);s.houseDecorOwned=p.getInt("house_decor_owned",1);s.sessionWins=p.getInt("session_wins",0);s.sessionPerfect=p.getInt("session_perfect",0);s.saveSchema=p.getInt("save_schema",1);s.reducedMotion=p.getInt("reduced_motion",0);s.largeText=p.getInt("large_text",0);s.hintsOn=p.getInt("hints_on",1);s.highContrast=p.getInt("high_contrast",0);s.colorBlindMode=p.getInt("color_blind_mode",0);s.accessibilityAnnouncements=p.getInt("accessibility_announcements",1);s.levelAttempts=p.getInt("level_attempts",0);s.levelFailures=p.getInt("level_failures",0);s.bossFailures=p.getInt("boss_failures",0);s.sanitize();s.validateReleaseState();return s;}
    void save(Context c){c.getSharedPreferences(PREFS,Context.MODE_PRIVATE).edit().putInt("coins",coins).putInt("stars",stars).putInt("level",level).putInt("eggs",eggs).putInt("house_level",houseLevel).putLong("owned_mask",ownedMask).putLong("achievement_mask",achievementMask).putString("level_stars",levelStars).putInt("daily_claim_day",dailyClaimDay).putInt("missions_done",missionsDone).putInt("streak",streak).putInt("best_streak",bestStreak).putInt("sound_on",soundOn).putInt("vibration_on",vibrationOn).putInt("mission_reward_tier",missionRewardTier).putInt("total_hatched",totalHatched).putInt("boss_wins",bossWins).putInt("reactions_unlocked",reactionsUnlocked).putInt("favorite_monster",favoriteMonster).putInt("xp",xp).putInt("player_level",playerLevel).putInt("best_score",bestScore).putInt("total_plays",totalPlays).putInt("perfect_bosses",perfectBosses).putInt("house_visits",houseVisits).putInt("care_points",carePoints).putInt("daily_streak",dailyStreak).putInt("best_daily_streak",bestDailyStreak).putInt("last_claim_day",lastClaimDay).putInt("challenge_wins",challengeWins).putInt("challenge_best",challengeBest).putInt("hatch_pity",hatchPity).putInt("rare_monsters",rareMonsters).putInt("boss_tokens",bossTokens).putInt("boss_chest_level",bossChestLevel).putInt("reaction_uses",reactionUses).putInt("friendship_level",friendshipLevel).putInt("house_decor",houseDecor).putInt("house_decor_owned",houseDecorOwned).putInt("session_wins",sessionWins).putInt("session_perfect",sessionPerfect).putInt("save_schema",saveSchema).putInt("reduced_motion",reducedMotion).putInt("large_text",largeText).putInt("hints_on",hintsOn).putInt("high_contrast",highContrast).putInt("color_blind_mode",colorBlindMode).putInt("accessibility_announcements",accessibilityAnnouncements).putInt("level_attempts",levelAttempts).putInt("level_failures",levelFailures).putInt("boss_failures",bossFailures).apply();}
    private void sanitize(){coins=Math.max(0,coins);stars=Math.max(0,stars);level=Math.max(1,Math.min(31,level));eggs=Math.max(0,eggs);houseLevel=Math.max(1,Math.min(5,houseLevel));playerLevel=Math.max(1,playerLevel);friendshipLevel=Math.max(1,Math.min(6,friendshipLevel));favoriteMonster=Math.max(0,Math.min(31,favoriteMonster));houseDecor=Math.max(0,Math.min(3,houseDecor));ownedMask|=1L;houseDecorOwned|=1;reactionsUnlocked=Math.max(1,Math.min(6,reactionsUnlocked));saveSchema=Math.max(2,saveSchema);reducedMotion=reducedMotion==0?0:1;largeText=largeText==0?0:1;hintsOn=hintsOn==0?0:1;highContrast=highContrast==0?0:1;colorBlindMode=colorBlindMode==0?0:1;accessibilityAnnouncements=accessibilityAnnouncements==0?0:1;levelAttempts=Math.max(0,levelAttempts);levelFailures=Math.max(0,levelFailures);bossFailures=Math.max(0,bossFailures);}
    void validateReleaseState(){coins=Math.max(0,coins);eggs=Math.max(0,eggs);xp=Math.max(0,xp);playerLevel=Math.max(1,playerLevel);streak=Math.max(0,streak);bestStreak=Math.max(streak,bestStreak);bossTokens=Math.max(0,bossTokens);bossChestLevel=Math.max(0,bossChestLevel);friendshipLevel=Math.max(1,Math.min(6,friendshipLevel));reactionUses=Math.max(0,reactionUses);carePoints=Math.max(0,carePoints);houseLevel=Math.max(1,Math.min(5,houseLevel));hatchPity=Math.max(0,Math.min(5,hatchPity));favoriteMonster=Math.max(0,Math.min(31,favoriteMonster));level=Math.max(1,Math.min(31,level));}
    void toggleReducedMotion(Context c){reducedMotion^=1;save(c);}void toggleLargeText(Context c){largeText^=1;save(c);}void toggleHints(Context c){hintsOn^=1;save(c);}void toggleHighContrast(Context c){highContrast^=1;save(c);}void toggleColorBlindMode(Context c){colorBlindMode^=1;save(c);}void toggleAccessibilityAnnouncements(Context c){accessibilityAnnouncements^=1;save(c);}void toggleSound(Context c){soundOn^=1;save(c);}void toggleVibration(Context c){vibrationOn^=1;save(c);}
    int starsFor(int n){String[] a=levelStars.split(",",-1);if(n<1||n>a.length)return 0;try{return Integer.parseInt(a[n-1]);}catch(Exception e){return 0;}}private int parse(String x){try{return Integer.parseInt(x);}catch(Exception e){return 0;}}private void setStarsFor(int n,int v){String[] old=levelStars.isEmpty()?new String[0]:levelStars.split(",",-1);int size=Math.max(n,old.length);StringBuilder b=new StringBuilder();for(int i=1;i<=size;i++){int x=i<=old.length?parse(old[i-1]):0;if(i==n)x=Math.max(x,v);if(i>1)b.append(',');b.append(x);}levelStars=b.toString();}
    boolean isBoss(int n){return n%5==0;}int safeStage(int n){return Math.max(1,Math.min(30,n));}int unlockedStage(){int u=1;for(int n=1;n<=30;n++)if(starsFor(n)>0)u=Math.max(u,Math.min(30,n+1));return u;}boolean isStageUnlocked(int n){return n>=1&&n<=unlockedStage();}boolean levelUnlocked(int n){return n>=1&&n<=30&&n<=level;}int worldForStage(int n){return Math.max(1,Math.min(3,((n-1)/10)+1));}String worldName(int w){return w==1?"Bosque Sorridente":w==2?"Ilhas de Açúcar":"Céu das Estrelas";}int targetTapsForLevel(int n){return isBoss(n)?10+worldForStage(n)*2:6+worldForStage(n);}int rewardForLevel(int n,int e){int b=8+worldForStage(n)*4;if(isBoss(n))b+=12;return b+Math.max(1,e)*3;}
    void beginLevel(Context c){levelAttempts++;save(c);}void failLevel(Context c,int n){levelFailures++;if(isBoss(n))bossFailures++;streak=0;save(c);}int completionRate(){return levelAttempts<=0?100:Math.max(0,Math.min(100,((levelAttempts-levelFailures)*100)/levelAttempts));}
    void finishLevel(Context c,int n,int e){e=Math.max(1,Math.min(3,e));coins+=rewardForLevel(n,e);totalPlays++;sessionWins++;if(e==3)sessionPerfect++;if(isBoss(n)&&e==3)perfectBosses++;int before=starsFor(n);setStarsFor(n,e);stars+=Math.max(0,e-before);if(isBoss(n)){bossWins++;bossTokens+=e;reactionsUnlocked=Math.min(6,1+bossWins);}streak++;bestStreak=Math.max(bestStreak,streak);if(n>=level)level=Math.min(31,n+1);addXp(e*20+(isBoss(n)?40:0));if(level%3==0)eggs++;if(e==3)missionsDone++;save(c);}
    private void addXp(int a){xp+=Math.max(0,a);while(xp>=xpNeeded()){xp-=xpNeeded();playerLevel++;coins+=15;}}int xpNeeded(){return 100+(playerLevel-1)*25;}
    int currentDay(){return(int)(System.currentTimeMillis()/86400000L);}boolean dailyAvailable(){return dailyClaimDay!=currentDay();}int nextDailyReward(){int n=lastClaimDay==currentDay()-1?dailyStreak+1:1;return 20+Math.min(30,Math.max(0,n-1)*5);}boolean claimDaily(Context c){int d=currentDay();if(dailyClaimDay==d)return false;dailyStreak=lastClaimDay==d-1?dailyStreak+1:1;bestDailyStreak=Math.max(bestDailyStreak,dailyStreak);lastClaimDay=d;dailyClaimDay=d;coins+=nextDailyReward();if(dailyStreak%3==0)eggs++;save(c);return true;}
    String reactionForProgress(){String[] r={"Que legal!","Uhuu!","Você conseguiu!","Incrível!","Super!","Amizade máxima!"};return r[Math.max(0,Math.min(5,reactionsUnlocked-1))];}String useReaction(Context c){reactionUses++;if(reactionUses%5==0&&friendshipLevel<6){friendshipLevel++;coins+=5;}save(c);return reactionForProgress();}int friendshipGoal(){return friendshipLevel>=6?0:5-(reactionUses%5);}int friendshipProgress(){return Math.max(0,reactionUses%5);}
    boolean setFavorite(Context c,int idx){if(idx<0||idx>31||(ownedMask&(1L<<idx))==0)return false;favoriteMonster=idx;save(c);return true;}boolean collectionComplete(){return Long.bitCount(ownedMask)>=32;}int collectionCount(){return Long.bitCount(ownedMask);}int achievementCount(){return Long.bitCount(achievementMask);}int rareOwnedCount(){int n=0;for(int i=24;i<32;i++)if((ownedMask&(1L<<i))!=0)n++;return n;}boolean isRareMonster(int i){return i>=24&&i<32;}int pityRemaining(){return Math.max(0,5-hatchPity);}int eggsUntilRare(){return collectionComplete()?0:Math.max(0,5-hatchPity);}
    boolean hatch(Context c){if(eggs<=0||collectionComplete())return false;eggs--;totalHatched++;hatchPity++;int idx=nextLockedMonster();if(idx>=0){ownedMask|=1L<<idx;if(isRareMonster(idx)){rareMonsters++;hatchPity=0;}}save(c);return idx>=0;}private int nextLockedMonster(){if(collectionComplete())return-1;if(hatchPity>=5)for(int i=24;i<32;i++)if((ownedMask&(1L<<i))==0)return i;for(int i=0;i<32;i++)if((ownedMask&(1L<<i))==0)return i;return-1;}
    int nextMissionTarget(){return(missionRewardTier+1)*3;}boolean claimMissionReward(Context c){if(missionsDone<nextMissionTarget())return false;missionRewardTier++;coins+=30;if(missionRewardTier%2==0)eggs++;save(c);return true;}int bossChestCost(){return 6+bossChestLevel*2;}boolean claimBossChest(Context c){int cost=bossChestCost();if(bossTokens<cost)return false;bossTokens-=cost;bossChestLevel++;coins+=25+bossChestLevel*5;eggs++;save(c);return true;}
    String houseStage(){String[] n={"Cantinho Fofo","Ninho Colorido","Casa Feliz","Mansão Monstrinha","Castelo da Amizade"};return n[houseLevel-1];}int careGoal(){return 5+houseLevel*3;}int houseNextCare(){return houseLevel>=5?0:Math.max(0,houseLevel*5-carePoints);}boolean careAtHouse(Context c){houseVisits++;carePoints++;coins+=2;if(carePoints>=careGoal()){carePoints=0;coins+=10;if(houseLevel<5)houseLevel++;}save(c);return true;}boolean upgradeHouse(Context c){int cost=40*houseLevel;if(coins<cost||houseLevel>=5)return false;coins-=cost;houseLevel++;save(c);return true;}
    int decorCost(int i){return i==1?35:i==2?60:i==3?90:0;}String decorName(){String[] n={"Clássica","Floresta","Estrelas","Doce"};return n[Math.max(0,Math.min(3,houseDecor))];}boolean hasDecor(int i){return i>=0&&i<=3&&(houseDecorOwned&(1<<i))!=0;}boolean selectOrBuyDecor(Context c,int i){if(i<0||i>3)return false;if(hasDecor(i)){houseDecor=i;save(c);return true;}int cost=decorCost(i);if(coins<cost)return false;coins-=cost;houseDecorOwned|=1<<i;houseDecor=i;save(c);return true;}
    void finishChallenge(Context c,int score){challengeWins++;challengeBest=Math.max(challengeBest,score);coins+=5+Math.min(20,score);save(c);}int unlockedLevelCount(){return Math.max(1,Math.min(30,level));}
    float textScale(){return largeText==1?1.18f:1f;}boolean shouldAnimate(){return reducedMotion==0;}int minimumTouchTargetDp(){return 48;}String accessibilitySummary(){return(largeText==1?"Texto grande":"Texto padrão")+" • "+(reducedMotion==1?"Movimento reduzido":"Animações ativas")+" • "+(highContrast==1?"Alto contraste":"Contraste padrão");}String collectionMilestone(){int n=collectionCount();if(n>=32)return"Coleção completa!";if(n>=24)return"Explorador lendário: 24/32";if(n>=16)return"Grande colecionador: 16/32";if(n>=8)return"Colecionador iniciante: 8/32";return"Próximo marco: "+(8-n)+" monstrinho(s)";}
}
