package com.caeless.monstrinhos;

import android.app.Activity;
import com.android.billingclient.api.*;
import com.google.android.gms.ads.*;
import com.google.android.gms.ads.interstitial.*;
import com.google.android.gms.ads.rewarded.*;
import java.util.*;

final class MonetizationManager implements PurchasesUpdatedListener {
    static final String COINS_SMALL="coins_small",COINS_MEDIUM="coins_medium",REMOVE_ADS="remove_ads";
    static final int SMALL_COINS=300,MEDIUM_COINS=900,REWARDED_COINS=30;
    interface Listener{void onCatalogChanged();void onPurchaseGranted(String id,int coins,boolean removeAds);void onRewardedAdEarned(int coins);void onMessage(String msg);}
    private final Activity activity;private final Listener listener;private final Map<String,ProductDetails> products=new HashMap<>();private final Set<String> processing=new HashSet<>();
    private BillingClient billing;private RewardedAd rewarded;private InterstitialAd interstitial;private boolean ready;
    MonetizationManager(Activity a,Listener l){activity=a;listener=l;}
    void start(){
        billing=BillingClient.newBuilder(activity).setListener(this).enablePendingPurchases(PendingPurchasesParams.newBuilder().enableOneTimeProducts().build()).enableAutoServiceReconnection().build();
        billing.startConnection(new BillingClientStateListener(){public void onBillingSetupFinished(BillingResult r){ready=r.getResponseCode()==BillingClient.BillingResponseCode.OK;if(ready){queryProducts();restorePurchases();}else listener.onMessage("Loja Google Play indisponível.");}public void onBillingServiceDisconnected(){ready=false;}});
        RequestConfiguration c=MobileAds.getRequestConfiguration().toBuilder().setTagForChildDirectedTreatment(RequestConfiguration.TAG_FOR_CHILD_DIRECTED_TREATMENT_TRUE).setTagForUnderAgeOfConsent(RequestConfiguration.TAG_FOR_UNDER_AGE_OF_CONSENT_TRUE).setMaxAdContentRating(RequestConfiguration.MAX_AD_CONTENT_RATING_G).build();
        MobileAds.setRequestConfiguration(c);MobileAds.initialize(activity,s->{loadRewarded();loadInterstitial();});
    }
    private void queryProducts(){List<QueryProductDetailsParams.Product> l=new ArrayList<>();for(String id:new String[]{COINS_SMALL,COINS_MEDIUM,REMOVE_ADS})l.add(QueryProductDetailsParams.Product.newBuilder().setProductId(id).setProductType(BillingClient.ProductType.INAPP).build());billing.queryProductDetailsAsync(QueryProductDetailsParams.newBuilder().setProductList(l).build(),(r,d)->{if(r.getResponseCode()==BillingClient.BillingResponseCode.OK){products.clear();for(ProductDetails p:d.getProductDetailsList())products.put(p.getProductId(),p);listener.onCatalogChanged();}});}
    String priceFor(String id){ProductDetails p=products.get(id);if(p==null)return ready?"Configurar no Play":"Conectando...";List<ProductDetails.OneTimePurchaseOfferDetails> o=p.getOneTimePurchaseOfferDetailsList();return o==null||o.isEmpty()?"Google Play":o.get(0).getFormattedPrice();}
    void launchPurchase(String id){if(!ready){listener.onMessage("Conectando à Google Play...");return;}ProductDetails p=products.get(id);if(p==null){queryProducts();listener.onMessage("Produto ainda não publicado no Play Console.");return;}BillingFlowParams.ProductDetailsParams.Builder pb=BillingFlowParams.ProductDetailsParams.newBuilder().setProductDetails(p);List<ProductDetails.OneTimePurchaseOfferDetails> o=p.getOneTimePurchaseOfferDetailsList();if(o!=null&&!o.isEmpty()){String t=o.get(0).getOfferToken();if(t!=null&&!t.isEmpty())pb.setOfferToken(t);}BillingResult r=billing.launchBillingFlow(activity,BillingFlowParams.newBuilder().setProductDetailsParamsList(Collections.singletonList(pb.build())).setIsOfferPersonalized(false).build());if(r.getResponseCode()!=BillingClient.BillingResponseCode.OK)listener.onMessage("Compra indisponível: "+r.getDebugMessage());}
    public void onPurchasesUpdated(BillingResult r,List<Purchase> ps){if(r.getResponseCode()==BillingClient.BillingResponseCode.OK&&ps!=null)for(Purchase p:ps)process(p);else if(r.getResponseCode()!=BillingClient.BillingResponseCode.USER_CANCELED)listener.onMessage("Compra não concluída.");}
    private void restorePurchases(){billing.queryPurchasesAsync(QueryPurchasesParams.newBuilder().setProductType(BillingClient.ProductType.INAPP).build(),(r,ps)->{if(r.getResponseCode()==BillingClient.BillingResponseCode.OK)for(Purchase p:ps)process(p);});}
    private void process(Purchase p){if(p.getPurchaseState()!=Purchase.PurchaseState.PURCHASED)return;List<String> ids=p.getProducts();if(ids.contains(REMOVE_ADS)){if(p.isAcknowledged())listener.onPurchaseGranted(REMOVE_ADS,0,true);else billing.acknowledgePurchase(AcknowledgePurchaseParams.newBuilder().setPurchaseToken(p.getPurchaseToken()).build(),r->{if(r.getResponseCode()==BillingClient.BillingResponseCode.OK)listener.onPurchaseGranted(REMOVE_ADS,0,true);});return;}String id=ids.contains(COINS_MEDIUM)?COINS_MEDIUM:(ids.contains(COINS_SMALL)?COINS_SMALL:null);if(id==null||!processing.add(p.getPurchaseToken()))return;int coins=id.equals(COINS_MEDIUM)?MEDIUM_COINS:SMALL_COINS;billing.consumeAsync(ConsumeParams.newBuilder().setPurchaseToken(p.getPurchaseToken()).build(),(r,t)->{processing.remove(t);if(r.getResponseCode()==BillingClient.BillingResponseCode.OK)listener.onPurchaseGranted(id,coins,false);else listener.onMessage("Compra recebida; aguardando confirmação.");});}
    private void loadRewarded(){RewardedAd.load(activity,activity.getString(R.string.admob_rewarded_id),new AdRequest.Builder().build(),new RewardedAdLoadCallback(){public void onAdLoaded(RewardedAd a){rewarded=a;listener.onCatalogChanged();}public void onAdFailedToLoad(LoadAdError e){rewarded=null;}});}
    private void loadInterstitial(){InterstitialAd.load(activity,activity.getString(R.string.admob_interstitial_id),new AdRequest.Builder().build(),new InterstitialAdLoadCallback(){public void onAdLoaded(InterstitialAd a){interstitial=a;}public void onAdFailedToLoad(LoadAdError e){interstitial=null;}});}
    void showRewarded(){RewardedAd a=rewarded;if(a==null){listener.onMessage("Vídeo ainda está carregando.");loadRewarded();return;}rewarded=null;a.setFullScreenContentCallback(new FullScreenContentCallback(){public void onAdDismissedFullScreenContent(){loadRewarded();}public void onAdFailedToShowFullScreenContent(AdError e){loadRewarded();}});a.show(activity,r->listener.onRewardedAdEarned(REWARDED_COINS));}
    boolean showInterstitial(Runnable after){InterstitialAd a=interstitial;if(a==null){loadInterstitial();after.run();return false;}interstitial=null;a.setFullScreenContentCallback(new FullScreenContentCallback(){public void onAdDismissedFullScreenContent(){loadInterstitial();after.run();}public void onAdFailedToShowFullScreenContent(AdError e){loadInterstitial();after.run();}});a.show(activity);return true;}
    void close(){if(billing!=null)billing.endConnection();}
}
