package com.caeless.monstrinhos;

import android.content.Context;import android.graphics.*;import android.os.Bundle;import android.view.*;import java.util.Random;

public final class MonstrinhosView extends View{
 private final Paint p=new Paint(1);private final Random rng=new Random();private GameState s;private int screen=0,selectedLevel=1,taps=0,misses=0,levelPage=0,albumPage=0,challengeScore=0;private float targetX=.5f,targetY=.5f;private String reaction="";
 private final int NAVY=Color.rgb(35,38,92),PURPLE=Color.rgb(102,74,190),BLUE=Color.rgb(72,177,238),GREEN=Color.rgb(105,205,96),GOLD=Color.rgb(255,196,55),CREAM=Color.rgb(255,247,218);
 public MonstrinhosView(Context c){super(c);s=GameState.load(c);setFocusable(true);setContentDescription("Jogo Monstrinhos. Toque duas vezes para interagir.");}
 public void persistProgress(){s.save(getContext());} public void saveSession(Bundle b){b.putInt("screen",screen);b.putInt("selected",selectedLevel);b.putInt("taps",taps);b.putInt("misses",misses);b.putInt("levelPage",levelPage);b.putInt("albumPage",albumPage);b.putInt("challengeScore",challengeScore);b.putFloat("targetX",targetX);b.putFloat("targetY",targetY);} public void restoreSession(Bundle b){screen=Math.max(0,Math.min(6,b.getInt("screen",0)));selectedLevel=s.safeStage(b.getInt("selected",1));taps=Math.max(0,b.getInt("taps",0));misses=Math.max(0,b.getInt("misses",0));levelPage=Math.max(0,Math.min(2,b.getInt("levelPage",0)));albumPage=Math.max(0,Math.min(1,b.getInt("albumPage",0)));challengeScore=Math.max(0,b.getInt("challengeScore",0));targetX=b.getFloat("targetX",.5f);targetY=b.getFloat("targetY",.5f);}
 private void text(Canvas c,String t,float x,float y,float z,int color){p.setColor(color);p.setTextSize(z*s.textScale());p.setTypeface(Typeface.create("sans",Typeface.BOLD));p.setShadowLayer(2,0,2,0x55000000);c.drawText(t,x,y,p);p.clearShadowLayer();} private void box(Canvas c,float l,float t,float r,float b,int color){p.setColor(color);c.drawRoundRect(l,t,r,b,30,30,p);} private void sky(Canvas c,float w,float h){Paint q=new Paint();q.setShader(new LinearGradient(0,0,0,h,0xff68c9ff,0xffeaf9ff,Shader.TileMode.CLAMP));c.drawRect(0,0,w,h,q);p.setColor(0x55ffffff);for(int i=0;i<8;i++)c.drawCircle((i*137)%Math.max(1,(int)w),80+(i%3)*75,45,p);p.setColor(0xff62bd62);c.drawOval(-80,h*.72f,w*.65f,h*1.05f,p);p.setColor(0xff3c9b55);c.drawOval(w*.35f,h*.76f,w+100,h*1.05f,p);} private void top(Canvas c,String title,float w){box(c,18,18,w-18,118,NAVY);text(c,title,38,66,28,Color.WHITE);text(c,"🪙 "+s.coins+"   ⭐ "+s.stars+"   🥚 "+s.eggs,38,101,17,GOLD);} private void button(Canvas c,String label,float l,float t,float r,float b,int color){p.setStyle(Paint.Style.FILL);box(c,l,t,r,b,color);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(5);p.setColor(0x66000000);c.drawRoundRect(l,t,r,b,30,30,p);p.setStyle(Paint.Style.FILL);p.setTextAlign(Paint.Align.CENTER);text(c,label,(l+r)/2,(t+b)/2+10,22,Color.WHITE);p.setTextAlign(Paint.Align.LEFT);} private void mascot(Canvas c,float x,float y,float scale,int color){p.setColor(color);c.drawOval(x-55*scale,y-50*scale,x+55*scale,y+55*scale,p);c.drawCircle(x-35*scale,y-40*scale,25*scale,p);c.drawCircle(x+35*scale,y-40*scale,25*scale,p);p.setColor(Color.WHITE);c.drawCircle(x-20*scale,y-8*scale,13*scale,p);c.drawCircle(x+20*scale,y-8*scale,13*scale,p);p.setColor(NAVY);c.drawCircle(x-20*scale,y-8*scale,6*scale,p);c.drawCircle(x+20*scale,y-8*scale,6*scale,p);p.setStyle(Paint.Style.STROKE);p.setStrokeWidth(5*scale);c.drawArc(x-23*scale,y+5*scale,x+23*scale,y+35*scale,5,170,false,p);p.setStyle(Paint.Style.FILL);}
 @Override protected void onDraw(Canvas c){float w=getWidth(),h=getHeight();sky(c,w,h);if(screen==0)home(c,w,h);else if(screen==1)stages(c,w,h);else if(screen==2)play(c,w,h);else if(screen==3)album(c,w,h);else if(screen==4)house(c,w,h);else if(screen==5)settings(c,w,h);else challenge(c,w,h);}
 private void home(Canvas c,float w,float h){top(c,"MONSTRINHOS",w);mascot(c,w*.5f,h*.28f,1.15f,BLUE);text(c,"Pequenas criaturas, grandes aventuras!",w*.08f,h*.42f,17,NAVY);button(c,"JOGAR",w*.12f,h*.47f,w*.88f,h*.58f,GREEN);button(c,s.dailyAvailable()?"🎁 PRESENTE":"✓ PRESENTE",w*.12f,h*.61f,w*.48f,h*.70f,GOLD);button(c,"🥚 OVO",w*.52f,h*.61f,w*.88f,h*.70f,PURPLE);button(c,"ÁLBUM",w*.06f,h*.76f,w*.29f,h*.85f,BLUE);button(c,"CASINHA",w*.31f,h*.76f,w*.55f,h*.85f,0xffe68a45);button(c,"AJUSTES",w*.57f,h*.76f,w*.94f,h*.85f,NAVY);button(c,"DESAFIO RÁPIDO",w*.18f,h*.88f,w*.82f,h*.97f,PURPLE);}
 private void stages(Canvas c,float w,float h){top(c,"🌿 "+s.worldName(levelPage+1),w);int start=levelPage*10+1;for(int i=0;i<10;i++){int n=start+i,row=i/5,col=i%5;float x=w*(.12f+col*.19f),y=h*(.29f+row*.25f);p.setColor(s.levelUnlocked(n)?(s.isBoss(n)?0xffff795e:BLUE):0xff9aa3ad);c.drawCircle(x,y,42,p);p.setTextAlign(Paint.Align.CENTER);text(c,""+n,x,y+8,20,Color.WHITE);text(c,"★"+s.starsFor(n),x,y+68,15,GOLD);p.setTextAlign(Paint.Align.LEFT);}button(c,"◀",w*.06f,h*.77f,w*.28f,h*.86f,NAVY);button(c,"▶",w*.72f,h*.77f,w*.94f,h*.86f,NAVY);button(c,"VOLTAR",w*.32f,h*.89f,w*.68f,h*.98f,PURPLE);}
 private void play(Canvas c,float w,float h){top(c,s.isBoss(selectedLevel)?"👑 CHEFE "+selectedLevel:"FASE "+selectedLevel,w);box(c,25,135,w-25,205,CREAM);text(c,"Toques "+taps+"/"+s.targetTapsForLevel(selectedLevel)+"  ❤ Erros "+misses+"/3",45,178,19,NAVY);mascot(c,w*targetX,h*targetY,1f,s.colorBlindMode==1?0xff0072b2:PURPLE);}
 private void album(Canvas c,float w,float h){top(c,"📖 COLEÇÃO "+s.collectionCount()+"/32",w);int start=albumPage*16;for(int i=0;i<16;i++){int idx=start+i,row=i/4,col=i%4;float x=w*(.14f+col*.24f),y=h*(.27f+row*.14f);boolean own=(s.ownedMask&(1L<<idx))!=0;mascot(c,x,y,.38f,own?new int[]{BLUE,GREEN,0xffff7d8d,GOLD,PURPLE}[idx%5]:0xffaab0ba);if(!own){p.setColor(0x88000000);c.drawCircle(x,y,25,p);}}button(c,"PÁGINA",w*.12f,h*.84f,w*.48f,h*.92f,BLUE);button(c,"VOLTAR",w*.52f,h*.84f,w*.88f,h*.92f,PURPLE);}
 private void house(Canvas c,float w,float h){top(c,"🏡 CASINHA",w);p.setColor(0xfff3b45a);c.drawRect(w*.22f,h*.33f,w*.78f,h*.63f,p);Path roof=new Path();roof.moveTo(w*.14f,h*.35f);roof.lineTo(w*.5f,h*.20f);roof.lineTo(w*.86f,h*.35f);roof.close();p.setColor(0xffd95f4d);c.drawPath(roof,p);mascot(c,w*.5f,h*.67f,.65f,BLUE);button(c,"❤ CARINHO",w*.08f,h*.75f,w*.46f,h*.84f,0xffff7597);button(c,"⬆ EVOLUIR",w*.54f,h*.75f,w*.92f,h*.84f,GREEN);button(c,"🎨 TEMA",w*.08f,h*.87f,w*.46f,h*.96f,GOLD);button(c,"VOLTAR",w*.54f,h*.87f,w*.92f,h*.96f,PURPLE);}
 private void settings(Canvas c,float w,float h){top(c,"⚙ AJUSTES",w);String[] a={"🔊 Som: "+(s.soundOn==1?"ON":"OFF"),"📳 Vibração: "+(s.vibrationOn==1?"ON":"OFF"),"💡 Dicas: "+(s.hintsOn==1?"ON":"OFF"),"♿ TalkBack: "+(s.accessibilityAnnouncements==1?"ON":"OFF")};for(int i=0;i<4;i++){box(c,w*.08f,h*(.22f+i*.12f),w*.92f,h*(.31f+i*.12f),Color.WHITE);text(c,a[i],w*.13f,h*(.275f+i*.12f),19,NAVY);}button(c,"ACESSIBILIDADE",w*.08f,h*.72f,w*.92f,h*.81f,BLUE);button(c,"VOLTAR",w*.25f,h*.87f,w*.75f,h*.96f,PURPLE);}
 private void challenge(Canvas c,float w,float h){top(c,"⚡ DESAFIO RÁPIDO",w);text(c,"Pontos "+challengeScore+"/10  ❤ "+(3-misses),35,170,20,NAVY);mascot(c,w*targetX,h*targetY,1f,GREEN);button(c,"VOLTAR",w*.30f,h*.88f,w*.70f,h*.97f,PURPLE);}
 @Override public boolean performClick(){super.performClick();return true;} private void announce(String m){if(s.accessibilityAnnouncements==1)announceForAccessibility(m);} @Override public boolean onTouchEvent(MotionEvent e){if(e.getAction()!=MotionEvent.ACTION_UP)return true;performClick();float x=e.getX(),y=e.getY(),w=getWidth(),h=getHeight();reaction="";if(screen==0){if(y>h*.47f&&y<h*.58f)screen=1;else if(y>h*.61f&&y<h*.70f){if(x<w*.5f)s.claimDaily(getContext());else s.hatch(getContext());}else if(y>h*.74f&&y<h*.87f){if(x<w*.30f)screen=3;else if(x<w*.56f)screen=4;else screen=5;}else if(y>h*.87f){screen=6;challengeScore=misses=0;}}else if(screen==1){if(y>h*.88f)screen=0;else if(y>h*.75f){if(x<w*.5f)levelPage=Math.max(0,levelPage-1);else levelPage=Math.min(2,levelPage+1);}else{int start=levelPage*10+1;for(int i=0;i<10;i++){int n=start+i,row=i/5,col=i%5;float cx=w*(.12f+col*.19f),cy=h*(.29f+row*.25f);if((x-cx)*(x-cx)+(y-cy)*(y-cy)<3000&&s.levelUnlocked(n)){selectedLevel=n;taps=misses=0;s.beginLevel(getContext());screen=2;break;}}}}else if(screen==2){float dx=x-w*targetX,dy=y-h*targetY;if(dx*dx+dy*dy<18000){taps++;if(s.shouldAnimate()){targetX=.2f+rng.nextFloat()*.6f;targetY=.32f+rng.nextFloat()*.35f;}if(taps>=s.targetTapsForLevel(selectedLevel)){s.finishLevel(getContext(),selectedLevel,misses==0?3:misses==1?2:1);screen=0;}}else if(++misses>=3){s.failLevel(getContext(),selectedLevel);screen=0;}}else if(screen==3){if(y>h*.82f){if(x<w*.5f)albumPage=1-albumPage;else screen=0;}}else if(screen==4){if(y>h*.85f){if(x<w*.5f)s.selectOrBuyDecor(getContext(),(s.houseDecor+1)%4);else screen=0;}else if(y>h*.73f){if(x<w*.5f)s.careAtHouse(getContext());else s.upgradeHouse(getContext());}}else if(screen==5){if(y>h*.85f)screen=0;else if(y>h*.20f&&y<h*.34f){if(x<w*.5f)s.toggleSound(getContext());else s.toggleVibration(getContext());}else if(y>h*.34f&&y<h*.58f){if(x<w*.5f)s.toggleHints(getContext());else s.toggleAccessibilityAnnouncements(getContext());}else if(y>h*.70f){if(x<w*.25f)s.toggleReducedMotion(getContext());else if(x<w*.5f)s.toggleLargeText(getContext());else if(x<w*.75f)s.toggleHighContrast(getContext());else s.toggleColorBlindMode(getContext());}}else{if(y>h*.86f)screen=0;else{float dx=x-w*targetX,dy=y-h*targetY;if(dx*dx+dy*dy<18000){challengeScore++;if(s.shouldAnimate()){targetX=.18f+rng.nextFloat()*.64f;targetY=.30f+rng.nextFloat()*.4f;}if(challengeScore>=10){s.finishChallenge(getContext(),challengeScore);screen=0;}}else if(++misses>=3){s.finishChallenge(getContext(),challengeScore);screen=0;}}}if(!reaction.isEmpty())announce(reaction);invalidate();return true;}
}
