package com.caeless.monstrinhos;

import android.content.Context;import android.graphics.*;import android.os.Bundle;import android.view.*;import java.util.Random;

public final class MonstrinhosView extends View{
 private final Paint p=new Paint(1);private final Random rng=new Random();private GameState s;private int screen=0,selectedLevel=1,taps=0,misses=0,levelPage=0,albumPage=0,challengeScore=0;private float targetX=.5f,targetY=.5f;private String reaction="";
 public MonstrinhosView(Context c){super(c);s=GameState.load(c);setFocusable(true);setContentDescription("Jogo Monstrinhos. Toque duas vezes para interagir.");}
 public void persistProgress(){s.save(getContext());}
 public void saveSession(Bundle b){b.putInt("screen",screen);b.putInt("selected",selectedLevel);b.putInt("taps",taps);b.putInt("misses",misses);b.putInt("levelPage",levelPage);b.putInt("albumPage",albumPage);b.putInt("challengeScore",challengeScore);b.putFloat("targetX",targetX);b.putFloat("targetY",targetY);}
 public void restoreSession(Bundle b){screen=Math.max(0,Math.min(6,b.getInt("screen",0)));selectedLevel=s.safeStage(b.getInt("selected",1));taps=Math.max(0,b.getInt("taps",0));misses=Math.max(0,b.getInt("misses",0));levelPage=Math.max(0,Math.min(2,b.getInt("levelPage",0)));albumPage=Math.max(0,Math.min(1,b.getInt("albumPage",0)));challengeScore=Math.max(0,b.getInt("challengeScore",0));targetX=Math.max(.15f,Math.min(.85f,b.getFloat("targetX",.5f)));targetY=Math.max(.25f,Math.min(.8f,b.getFloat("targetY",.5f)));}
 private void text(Canvas c,String t,float x,float y,float size,int color){p.setColor(color);p.setTextSize(size*s.textScale());p.setTypeface(Typeface.create("sans",Typeface.BOLD));c.drawText(t,x,y,p);}
 private void box(Canvas c,float l,float t,float r,float b,int color){p.setColor(color);c.drawRoundRect(l,t,r,b,28,28,p);}
 private int bg(){return s.highContrast==1?Color.rgb(245,245,245):Color.rgb(234,248,255);}private int ink(){return s.highContrast==1?Color.BLACK:Color.rgb(55,45,90);}
 @Override protected void onDraw(Canvas c){super.onDraw(c);c.drawColor(bg());float w=getWidth(),h=getHeight();if(screen==0)home(c,w,h);else if(screen==1)stages(c,w,h);else if(screen==2)play(c,w,h);else if(screen==3)album(c,w,h);else if(screen==4)house(c,w,h);else if(screen==5)settings(c,w,h);else challenge(c,w,h);}
 private void header(Canvas c,String title){text(c,title,30,65,30,ink());text(c,"🪙 "+s.coins+"   ⭐ "+s.stars+"   🥚 "+s.eggs,30,105,19,ink());}
 private void home(Canvas c,float w,float h){header(c,"MONSTRINHOS");text(c,"Nível "+s.playerLevel+" • Coleção "+s.collectionCount()+"/32",30,150,19,ink());box(c,w*.08f,h*.25f,w*.92f,h*.36f,0xff7bdff2);text(c,"JOGAR",w*.37f,h*.32f,30,ink());box(c,w*.08f,h*.40f,w*.92f,h*.50f,0xffffd166);text(c,s.dailyAvailable()?"PRESENTE +"+s.nextDailyReward():"PRESENTE COLETADO ✓",w*.17f,h*.46f,21,ink());box(c,w*.08f,h*.54f,w*.92f,h*.64f,0xffff9ff3);text(c,"ABRIR OVO",w*.30f,h*.60f,24,ink());text(c,"ÁLBUM",w*.10f,h*.76f,20,ink());text(c,"CASINHA",w*.38f,h*.76f,20,ink());text(c,"AJUSTES",w*.68f,h*.76f,20,ink());text(c,"DESAFIO RÁPIDO",w*.29f,h*.90f,20,ink());if(!reaction.isEmpty())text(c,reaction,30,h*.96f,15,ink());}
 private void stages(Canvas c,float w,float h){header(c,"ESCOLHA UMA FASE");int start=levelPage*10+1;text(c,s.worldName(levelPage+1),30,155,22,ink());for(int slot=0;slot<10;slot++){int n=start+slot,row=slot/5,col=slot%5;float l=w*(.035f+col*.193f),t=h*(.30f+row*.18f);box(c,l,t,l+w*.165f,t+h*.12f,s.levelUnlocked(n)?0xffa8e6cf:0xffcccccc);text(c,""+n,l+16,t+38,20,ink());text(c,"★"+s.starsFor(n),l+10,t+70,15,ink());}text(c,"◀ MUNDO",30,h*.79f,18,ink());text(c,"MUNDO ▶",w*.65f,h*.79f,18,ink());text(c,"VOLTAR",w*.40f,h*.92f,20,ink());}
 private void monster(Canvas c,float w,float h){float x=w*targetX,y=h*targetY;p.setColor(s.colorBlindMode==1?0xff0072b2:0xff8f6cff);c.drawCircle(x,y,58,p);p.setColor(Color.WHITE);c.drawCircle(x-20,y-12,9,p);c.drawCircle(x+20,y-12,9,p);p.setColor(Color.BLACK);c.drawCircle(x-20,y-12,4,p);c.drawCircle(x+20,y-12,4,p);}
 private void play(Canvas c,float w,float h){header(c,s.isBoss(selectedLevel)?"CHEFE "+selectedLevel:"FASE "+selectedLevel);text(c,"Toques "+taps+"/"+s.targetTapsForLevel(selectedLevel)+" • Erros "+misses+"/3",30,150,20,ink());if(s.hintsOn==1)text(c,"Toque no centro do monstrinho!",30,190,16,ink());monster(c,w,h);}
 private void album(Canvas c,float w,float h){header(c,"ÁLBUM • "+s.collectionCount()+"/32");text(c,s.collectionMilestone(),30,150,16,ink());int start=albumPage*16;for(int i=0;i<16;i++){int idx=start+i,row=i/4,col=i%4;float x=w*(.16f+col*.225f),y=h*(.28f+row*.13f);p.setColor((s.ownedMask&(1L<<idx))!=0?0xff8f6cff:0xffbbbbbb);c.drawCircle(x,y,32,p);text(c,""+(idx+1),x-12,y+7,14,Color.WHITE);}text(c,"TROCAR PÁGINA",w*.30f,h*.85f,18,ink());text(c,"VOLTAR",w*.40f,h*.94f,20,ink());}
 private void house(Canvas c,float w,float h){header(c,"CASINHA");text(c,s.houseStage(),30,170,26,ink());text(c,"Tema: "+s.decorName(),30,210,18,ink());text(c,"Carinho: "+s.carePoints+"/"+s.careGoal(),30,250,18,ink());box(c,w*.12f,h*.48f,w*.88f,h*.58f,0xffffd166);text(c,"DAR CARINHO",w*.30f,h*.54f,22,ink());box(c,w*.12f,h*.62f,w*.88f,h*.72f,0xffa8e6cf);text(c,"EVOLUIR CASINHA",w*.23f,h*.68f,20,ink());text(c,"TROCAR TEMA",w*.33f,h*.82f,18,ink());text(c,"VOLTAR",w*.40f,h*.94f,20,ink());}
 private void settings(Canvas c,float w,float h){header(c,"AJUSTES E MISSÕES");text(c,"Missão: "+s.missionsDone+"/"+s.nextMissionTarget(),30,165,18,ink());text(c,"RESGATAR MISSÃO",30,220,18,ink());text(c,"Som: "+(s.soundOn==1?"ON":"OFF")+"   Vibração: "+(s.vibrationOn==1?"ON":"OFF"),30,285,18,ink());text(c,"Dicas: "+(s.hintsOn==1?"ON":"OFF")+"   TalkBack: "+(s.accessibilityAnnouncements==1?"ON":"OFF"),30,350,17,ink());text(c,"Baú chefe: "+s.bossTokens+"/"+s.bossChestCost()+"   Amizade: "+s.friendshipLevel+"/6",30,415,16,ink());text(c,s.accessibilitySummary(),30,480,15,ink());text(c,"Movimento • Texto • Contraste • Cores",30,h*.84f,15,ink());text(c,"VOLTAR",w*.40f,h*.95f,20,ink());}
 private void challenge(Canvas c,float w,float h){header(c,"DESAFIO RÁPIDO");text(c,"Pontos "+challengeScore+"/10 • Erros "+misses+"/3",30,150,20,ink());monster(c,w,h);text(c,"VOLTAR",w*.40f,h*.92f,20,ink());}
 @Override public boolean performClick(){super.performClick();return true;}private void announce(String m){if(s.accessibilityAnnouncements==1)announceForAccessibility(m);}
 @Override public boolean onTouchEvent(android.view.MotionEvent e){if(e.getAction()!=MotionEvent.ACTION_UP)return true;performClick();float x=e.getX(),y=e.getY(),w=getWidth(),h=getHeight();reaction="";
  if(screen==0){if(y>h*.25f&&y<h*.36f)screen=1;else if(y>h*.40f&&y<h*.50f)reaction=s.claimDaily(getContext())?"Presente recebido!":"Volte amanhã!";else if(y>h*.54f&&y<h*.64f)reaction=s.hatch(getContext())?"Novo amigo descoberto!":"Você precisa de um ovo.";else if(y>h*.70f&&y<h*.80f){if(x<w*.33f)screen=3;else if(x<w*.63f)screen=4;else screen=5;}else if(y>h*.84f){screen=6;challengeScore=0;misses=0;targetX=.5f;targetY=.5f;}}
  else if(screen==1){if(y>h*.86f)screen=0;else if(y>h*.72f){if(x<w*.5f)levelPage=Math.max(0,levelPage-1);else levelPage=Math.min(2,levelPage+1);}else{int start=levelPage*10+1;for(int slot=0;slot<10;slot++){int n=start+slot,row=slot/5,col=slot%5;float l=w*(.035f+col*.193f),t=h*(.30f+row*.18f);if(x>=l&&x<=l+w*.165f&&y>=t&&y<=t+h*.12f&&s.levelUnlocked(n)){selectedLevel=s.safeStage(n);taps=misses=0;targetX=targetY=.5f;s.beginLevel(getContext());screen=2;break;}}}}
  else if(screen==2){float dx=x-w*targetX,dy=y-h*targetY;if(dx*dx+dy*dy<15000){taps++;if(s.shouldAnimate()){targetX=.2f+rng.nextFloat()*.6f;targetY=.32f+rng.nextFloat()*.32f;}else{targetX=targetY=.5f;}if(taps>=s.targetTapsForLevel(selectedLevel)){int earned=misses==0?3:misses==1?2:1;s.finishLevel(getContext(),selectedLevel,earned);reaction="Fase concluída! "+s.reactionForProgress();screen=0;}}else if(++misses>=3){s.failLevel(getContext(),selectedLevel);reaction="Quase! Tente novamente.";screen=0;}}
  else if(screen==3){if(y>h*.90f)screen=0;else if(y>h*.80f)albumPage=1-albumPage;else{int start=albumPage*16;for(int i=0;i<16;i++){int idx=start+i,row=i/4,col=i%4;float mx=w*(.16f+col*.225f),my=h*(.28f+row*.13f),dx=x-mx,dy=y-my;if(dx*dx+dy*dy<2500){reaction=s.setFavorite(getContext(),idx)?"Favorito atualizado!":"Descubra primeiro.";break;}}}}
  else if(screen==4){if(y>h*.90f)screen=0;else if(y>h*.48f&&y<h*.60f){s.careAtHouse(getContext());reaction="Carinho dado!";}else if(y>h*.60f&&y<h*.75f)reaction=s.upgradeHouse(getContext())?"Casinha evoluiu!":"Junte mais moedas.";else if(y>h*.75f){int next=(s.houseDecor+1)%4;reaction=s.selectOrBuyDecor(getContext(),next)?"Tema: "+s.decorName():"Faltam moedas.";}}
  else if(screen==5){if(y>h*.90f)screen=0;else if(y<260)reaction=s.claimMissionReward(getContext())?"Missão resgatada!":"Complete a missão.";else if(y<325){if(x<w*.5f)s.toggleSound(getContext());else s.toggleVibration(getContext());}else if(y<390){if(x<w*.5f)s.toggleHints(getContext());else s.toggleAccessibilityAnnouncements(getContext());}else if(y<455){if(x<w*.5f)reaction=s.claimBossChest(getContext())?"Baú aberto!":"Faltam fichas.";else reaction=s.useReaction(getContext());}else{if(x<w*.25f)s.toggleReducedMotion(getContext());else if(x<w*.5f)s.toggleLargeText(getContext());else if(x<w*.75f)s.toggleHighContrast(getContext());else s.toggleColorBlindMode(getContext());}}
  else{if(y>h*.86f)screen=0;else{float dx=x-w*targetX,dy=y-h*targetY;if(dx*dx+dy*dy<15000){challengeScore++;if(s.shouldAnimate()){targetX=.18f+rng.nextFloat()*.64f;targetY=.32f+rng.nextFloat()*.35f;}else targetX=targetY=.5f;if(challengeScore>=10){s.finishChallenge(getContext(),challengeScore);reaction="Desafio completo!";screen=0;}}else if(++misses>=3){s.finishChallenge(getContext(),challengeScore);reaction="Desafio terminou.";screen=0;}}}
  if(!reaction.isEmpty())announce(reaction);invalidate();return true;}
}
