name: Build Monstrinhos v6.8.8 Idioma Unico
on:
  workflow_dispatch:

jobs:
  hold:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Workflow temporariamente pausado enquanto o patch 688 e atualizado."
